import { useState } from 'react';
import { useProviders, type Provider } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { TrustIndicator } from '@/components/TrustIndicator';

export default function Providers() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en;
  const [search, setSearch] = useState(''); const [city, setCity] = useState(''); const [status, setStatus] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Provider | null>(null);
  const { data, isLoading } = useProviders({ q: search || undefined, accountStatus: status || undefined, limit: 20, cursor });
  const columns: OperationsColumn<Provider>[] = [{ key: 'provider', label: t('المزود', 'Provider'), sortable: true, render: p => <div><div className="font-medium">{p.nameAr || p.nameEn || p.displayName || '—'}</div><div dir="ltr" className="text-xs text-muted-foreground">{p.email || '—'}</div></div> }, { key: 'city', label: t('المدينة', 'City'), render: p => p.city || '—' }, { key: 'status', label: t('الحالة', 'Status'), render: p => <span className={p.suspensionStatus && p.suspensionStatus !== 'active' ? 'text-destructive' : 'text-emerald-500'}>{p.suspensionStatus && p.suspensionStatus !== 'active' ? t('موقوف', 'Suspended') : t('نشط', 'Active')}</span> }, { key: 'verification', label: t('التحقق', 'Verification'), render: p => <TrustIndicator value={p} language={language} /> }];
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">{t('المزودون', 'Providers')}</h1><p className="mt-1 text-muted-foreground">{t('إدارة المزودين مع معلومات الأسماء والاتصال المصرح بها.', 'Manage providers with authorized names and contact information.')}</p></div><OperationsTable<Provider> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('ابحث بالاسم أو البريد...', 'Search name or email…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><input value={city} onChange={e => setCity(e.target.value)} placeholder={t('المدينة', 'City')} className="h-9 w-28 rounded-md border bg-background px-2 text-sm" /><select value={status} onChange={e => setStatus(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All statuses')}</option><option value="active">{t('نشط', 'Active')}</option><option value="suspended">{t('موقوف', 'Suspended')}</option></select><ExportControls resource="providers" params={{ search, city, status }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={selected.nameAr || selected.nameEn || t('تفاصيل المزود', 'Provider details')} fields={[{ label: t('الاسم', 'Name'), value: selected.nameAr || selected.nameEn || selected.displayName }, { label: 'Email', value: selected.email }, { label: t('المدينة', 'City'), value: selected.city }, { label: 'UID', value: selected.id, technical: true }]} />}</div>;
}