import { useState } from 'react';
import { useRequests, type Request } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { useAdminAction } from '@/hooks/use-admin-action';
import { TrustIndicator } from '@/components/TrustIndicator';
import { Button } from '@/components/ui/button';

const statusText: Record<string, [string, string]> = { draft: ['مسودة', 'Draft'], pending: ['قيد الانتظار', 'Pending'], requested: ['مطلوب', 'Requested'], accepted: ['مقبول', 'Accepted'], in_progress: ['قيد التنفيذ', 'In progress'], completion_requested: ['طلب إكمال', 'Completion requested'], under_investigation: ['قيد التحقيق', 'Under investigation'], escalated: ['مصعّد', 'Escalated'], completed: ['مكتمل', 'Completed'], cancelled: ['ملغي', 'Cancelled'], frozen: ['مجمد', 'Frozen'] };
const cancellableRequestStates = new Set(['draft', 'pending', 'requested', 'accepted']);
const controllableRequestStates = new Set(['pending', 'requested', 'accepted', 'in_progress', 'completion_requested']);
export default function Requests() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en; const label = (value?: string) => value ? (statusText[value]?.[language === 'ar' ? 0 : 1] || value) : '—';
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [paymentState, setPaymentState] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Request | null>(null);
  const { data, isLoading } = useRequests({ q: search || undefined, status: status || undefined, paymentState: paymentState || undefined, limit: 20, cursor });
  const { triggerAction, ActionDialog } = useAdminAction();
  const act = (item: Request, action: string) => triggerAction({ targetType: 'request', targetId: item.id, action, title: t('إجراء الطلب', 'Request action'), description: t('يتحقق الخادم من آلة حالات الطلب قبل التنفيذ.', 'The server validates the request state machine before executing.') });
  const columns: OperationsColumn<Request>[] = [{ key: 'number', label: t('رقم الطلب', 'Request number'), sortable: true, render: r => r.publicRequestNumber || r.requestNumber || '—' }, { key: 'customer', label: t('العميل', 'Customer'), render: r => <div>{r.customer?.nameAr || r.customer?.nameEn || r.customer?.name || '—'}<div dir="ltr" className="text-xs text-muted-foreground">{r.customer?.email || '—'}</div></div> }, { key: 'provider', label: t('المزود', 'Provider'), render: r => r.provider?.nameAr || r.provider?.nameEn || r.provider?.name || '—' }, { key: 'equipment', label: t('المعدة', 'Equipment'), render: r => r.equipment?.title || r.equipment?.number || '—' }, { key: 'dates', label: t('الفترة', 'Rental dates'), render: r => <span className="text-xs">{r.rentalFrom || r.startDate || '—'} → {r.rentalTo || r.endDate || '—'}</span> }, { key: 'total', label: t('الإجمالي', 'Total'), render: r => r.totalAmount != null ? `SAR ${r.totalAmount}` : '—' }, { key: 'states', label: t('الحالات', 'States'), render: r => <div><div>{label(r.status)}</div><div className="text-xs text-muted-foreground">{r.paymentState || '—'}</div></div> }, { key: 'trust', label: t('الثقة', 'Trust'), render: r => <TrustIndicator value={r} language={language} /> }, { key: 'actions', label: t('إجراءات', 'Actions'), render: r => <div className="flex gap-1">{cancellableRequestStates.has(r.status) && <Button size="sm" variant="outline" onClick={() => act(r, 'cancel_request')}>{t('إلغاء', 'Cancel')}</Button>}{controllableRequestStates.has(r.status) && <Button size="sm" variant="ghost" onClick={() => act(r, 'freeze_request')}>{t('تجميد', 'Freeze')}</Button>}{controllableRequestStates.has(r.status) && <Button size="sm" variant="ghost" onClick={() => act(r, 'escalate_request')}>{t('تصعيد', 'Escalate')}</Button>}</div> }];
  return <div className="space-y-6"><ActionDialog /><div><h1 className="text-3xl font-bold tracking-tight">{t('الطلبات', 'Requests')}</h1><p className="mt-1 text-muted-foreground">{t('طلبات الإيجار بأرقام عامة وأسماء بشرية وحالات مترجمة.', 'Rental requests with public numbers, resolved names and translated states.')}</p></div><OperationsTable<Request> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('ابحث برقم الطلب أو الاسم...', 'Search request number or name…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><select value={status} onChange={e => setStatus(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All statuses')}</option>{Object.entries(statusText).map(([value, names]) => <option key={value} value={value}>{names[language === 'ar' ? 0 : 1]}</option>)}</select><select value={paymentState} onChange={e => setPaymentState(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل المدفوعات', 'All payment states')}</option><option value="paid">{t('مدفوع', 'Paid')}</option><option value="pending">{t('قيد الانتظار', 'Pending')}</option><option value="failed">{t('فشل', 'Failed')}</option></select><ExportControls resource="requests" params={{ q: search, status, paymentState }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={selected.publicRequestNumber || selected.requestNumber || t('تفاصيل الطلب', 'Request details')} fields={[{ label: t('رقم الطلب', 'Request number'), value: selected.publicRequestNumber || selected.requestNumber }, { label: t('العميل', 'Customer'), value: selected.customer?.nameAr || selected.customer?.nameEn || selected.customer?.name }, { label: t('المزود', 'Provider'), value: selected.provider?.nameAr || selected.provider?.nameEn || selected.provider?.name }, { label: t('الحالة', 'Status'), value: label(selected.status) }, { label: 'ID', value: selected.id, technical: true }, { label: 'Customer UID', value: selected.customerUid, technical: true }]} />}</div>;
}