import { useState } from 'react';
import { useComplaints, type Complaint } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { useAdminAction } from '@/hooks/use-admin-action';
import { TrustIndicator } from '@/components/TrustIndicator';
import { Button } from '@/components/ui/button';

export default function Complaints() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en; const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Complaint | null>(null); const { data, isLoading } = useComplaints({ q: search || undefined, status: status || undefined, limit: 20, cursor }); const { triggerAction, actionDialog } = useAdminAction(); const act = (c: Complaint, action: string) => triggerAction({ targetType: 'complaint', targetId: c.id, action, title: t('إجراء الشكوى', 'Complaint action'), description: t('يتحقق الخادم من حالة الشكوى.', 'The server validates complaint state.') });
  const columns: OperationsColumn<Complaint>[] = [{ key: 'complaint', label: t('الشكوى', 'Complaint'), render: c => <div className="max-w-[18rem]"><div className="font-medium truncate">{c.description || '—'}</div><div className="text-xs text-muted-foreground">{c.requestNumber || '—'}</div></div> }, { key: 'customer', label: t('العميل', 'Customer'), render: c => c.customer?.nameAr || c.customer?.nameEn || c.customer?.name || '—' }, { key: 'provider', label: t('المزود', 'Provider'), render: c => c.provider?.nameAr || c.provider?.nameEn || c.provider?.name || '—' }, { key: 'status', label: t('الحالة', 'Status'), render: c => c.status }, { key: 'trust', label: t('الثقة', 'Trust'), render: c => <TrustIndicator value={c} language={language} /> }, { key: 'actions', label: t('إجراءات', 'Actions'), render: c => !['resolved', 'closed'].includes(c.status) ? <div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => act(c, 'review_complaint')}>{t('مراجعة', 'Review')}</Button><Button size="sm" variant="ghost" onClick={() => act(c, 'resolve_complaint')}>{t('حل', 'Resolve')}</Button><Button size="sm" variant="ghost" onClick={() => act(c, 'close_complaint')}>{t('إغلاق', 'Close')}</Button></div> : null }];
  return <div className="space-y-6">{actionDialog}<div><h1 className="text-3xl font-bold tracking-tight">{t('الشكاوى', 'Complaints')}</h1><p className="mt-1 text-muted-foreground">{t('إدارة النزاعات مع أسماء الأطراف.', 'Manage disputes with resolved party names.')}</p></div><OperationsTable<Complaint> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('ابحث في الشكاوى...', 'Search complaints…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><select value={status} onChange={e => setStatus(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All statuses')}</option><option value="open">{t('مفتوحة', 'Open')}</option><option value="under_review">{t('تحت المراجعة', 'Under review')}</option><option value="resolved">{t('محلولة', 'Resolved')}</option><option value="closed">{t('مغلقة', 'Closed')}</option></select><ExportControls resource="complaints" params={{ q: search, status }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={t('تفاصيل الشكوى', 'Complaint details')} fields={[{ label: t('الوصف', 'Description'), value: selected.description }, { label: t('العميل', 'Customer'), value: selected.customer?.nameAr || selected.customer?.nameEn || selected.customer?.name }, { label: t('المزود', 'Provider'), value: selected.provider?.nameAr || selected.provider?.nameEn || selected.provider?.name }, { label: t('الحالة', 'Status'), value: selected.status }, { label: 'Complaint ID', value: selected.id, technical: true }]} />}</div>;
}