import { useState } from 'react';
import { userErrorMessage } from '@/lib/error-messages';
import { FileDown } from 'lucide-react';
import { useInvoices, fetchApiBinary, downloadBlob, type Invoice } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { CommercialBreakdown } from '@/components/commercial-breakdown';

export default function Invoices() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en; const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Invoice | null>(null); const [downloading, setDownloading] = useState<string>(); const { toast } = useToast(); const { data, isLoading } = useInvoices({ q: search || undefined, status: status || undefined, limit: 20, cursor });
  const downloadPdf = async (item: Invoice) => { setDownloading(item.id); try { const result = await fetchApiBinary(`/invoices/${encodeURIComponent(item.id)}.pdf`); downloadBlob(result.blob, result.filename || `${item.invoiceNumber || item.id}.pdf`); } catch (error) { toast({ title: t('تعذر تنزيل الفاتورة', 'Invoice download failed'), description: userErrorMessage(error, language), variant: 'destructive' }); } finally { setDownloading(undefined); } };
  const columns: OperationsColumn<Invoice>[] = [{ key: 'invoice', label: t('الفاتورة', 'Invoice'), sortable: true, render: i => i.invoiceNumber || i.id }, { key: 'request', label: t('الطلب', 'Request'), render: i => i.requestNumber || i.request?.requestNumber || '—' }, { key: 'people', label: t('الأطراف', 'Parties'), render: i => <div>{i.customer?.nameAr || i.customer?.nameEn || i.customer?.name || '—'}<div className="text-xs text-muted-foreground">{i.provider?.nameAr || i.provider?.nameEn || i.provider?.name || '—'}</div></div> }, { key: 'amount', label: t('المبلغ', 'Amount'), render: i => `SAR ${i.totalAmount || 0}` }, { key: 'status', label: t('الحالة', 'Status'), render: i => i.status }, { key: 'actions', label: t('تنزيل', 'Download'), render: i => <Button size="sm" variant="outline" onClick={() => downloadPdf(i)} disabled={downloading === i.id}><FileDown className="me-2 h-4 w-4" />PDF</Button> }];
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight">{t('الفواتير', 'Invoices')}</h1><p className="mt-1 text-muted-foreground">{t('فواتير موثوقة من بيانات الخادم مع تنزيل PDF.', 'Trusted invoices from server data with PDF download.')}</p></div><OperationsTable<Invoice> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('رقم الفاتورة أو الطلب...', 'Invoice or request number…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><select value={status} onChange={e => setStatus(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All statuses')}</option><option value="paid">{t('مدفوعة', 'Paid')}</option><option value="issued">{t('صادرة', 'Issued')}</option></select><ExportControls resource="invoices" params={{ q: search, status }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={selected.invoiceNumber || t('تفاصيل الفاتورة', 'Invoice details')} fields={[{ label: t('رقم الفاتورة', 'Invoice number'), value: selected.invoiceNumber }, { label: t('الطلب', 'Request'), value: selected.requestNumber || selected.request?.requestNumber }, { label: t('المبلغ', 'Amount'), value: `SAR ${selected.totalAmount || 0}` }, { label: 'Invoice ID', value: selected.id, technical: true }]}>
  <CommercialBreakdown snapshot={(selected as any).commercialSnapshot} legacyTotal={selected.totalAmount} />
</OperationDetails>}</div>;
}