import { useState } from 'react';
import { usePayments, type Payment } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { useAdminAction } from '@/hooks/use-admin-action';
import { Button } from '@/components/ui/button';

export default function Payments() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en; const [search, setSearch] = useState(''); const [state, setState] = useState(''); const [provider, setProvider] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Payment | null>(null); const { data, isLoading } = usePayments({ q: search || undefined, state: state || undefined, provider: provider || undefined, limit: 20, cursor }); const { triggerAction, actionDialog } = useAdminAction();
  const columns: OperationsColumn<Payment>[] = [{ key: 'request', label: t('الطلب', 'Request'), render: p => p.requestNumber || p.request?.requestNumber || '—' }, { key: 'people', label: t('الأطراف', 'Parties'), render: p => <div>{p.customer?.nameAr || p.customer?.nameEn || p.customer?.name || '—'}<div className="text-xs text-muted-foreground">{p.provider?.nameAr || p.provider?.nameEn || p.provider?.name || '—'}</div></div> }, { key: 'provider', label: t('بوابة الدفع', 'Payment provider'), render: p => <div>{p.providerName || '—'}<div className="font-mono text-xs text-muted-foreground">{p.providerReference || '—'}</div></div> }, { key: 'amount', label: t('المبلغ', 'Amount'), sortable: true, render: p => `SAR ${p.amount}` }, { key: 'state', label: t('الحالة', 'State'), render: p => p.state }, { key: 'actions', label: t('إجراءات', 'Actions'), render: p => p.state === 'paid' ? <Button size="sm" variant="outline" onClick={() => triggerAction({ targetType: 'payment', targetId: p.id, action: 'request_refund', title: t('طلب استرداد', 'Request refund'), description: t('يتم التحقق من الدفع في الخادم.', 'The server validates this payment.'), payload: { amount: p.amount } })}>{t('استرداد', 'Refund')}</Button> : null }];
  return <div className="space-y-6">{actionDialog}<div><h1 className="text-3xl font-bold tracking-tight">{t('المدفوعات', 'Payments')}</h1><p className="mt-1 text-muted-foreground">{t('مراقبة مالية بأسماء الطلبات ومراجع البوابات.', 'Financial monitoring with request names and gateway references.')}</p></div><OperationsTable<Payment> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('رقم الطلب أو المرجع...', 'Request number or reference…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><select value={state} onChange={e => setState(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All states')}</option><option value="paid">{t('مدفوع', 'Paid')}</option><option value="failed">{t('فشل', 'Failed')}</option><option value="pending">{t('قيد الانتظار', 'Pending')}</option></select><input value={provider} onChange={e => setProvider(e.target.value)} placeholder={t('البوابة', 'Provider')} className="h-9 w-24 rounded-md border bg-background px-2 text-sm" /><ExportControls resource="payments" params={{ q: search, state, provider }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={selected.requestNumber || selected.request?.requestNumber || t('تفاصيل الدفع', 'Payment details')} fields={[{ label: t('العميل', 'Customer'), value: selected.customer?.nameAr || selected.customer?.nameEn || selected.customer?.name }, { label: t('المبلغ', 'Amount'), value: `SAR ${selected.amount}` }, { label: t('الحالة', 'State'), value: selected.state }, { label: t('مرجع المزود', 'Provider reference'), value: selected.providerReference }, { label: 'Payment ID', value: selected.id, technical: true }]} />}</div>;
}