import { useState } from 'react';
import { useRefunds, type Refund } from '@/lib/api';
import { useAppState } from '@/lib/app-state';
import { OperationsTable, type OperationsColumn } from '@/components/operations-table';
import { OperationDetails } from '@/components/operation-details';
import { ExportControls } from '@/components/export-controls';
import { useAdminAction } from '@/hooks/use-admin-action';
import { Button } from '@/components/ui/button';

export default function Refunds() {
  const { language } = useAppState(); const t = (ar: string, en: string) => language === 'ar' ? ar : en; const [search, setSearch] = useState(''); const [state, setState] = useState(''); const [cursor, setCursor] = useState<string>(); const [history, setHistory] = useState<string[]>([]); const [selected, setSelected] = useState<Refund | null>(null); const { data, isLoading } = useRefunds({ q: search || undefined, state: state || undefined, limit: 20, cursor }); const { triggerAction, actionDialog } = useAdminAction();
  const act = (r: Refund, action: string) => triggerAction({ targetType: 'refund', targetId: r.id, action, title: t('قرار الاسترداد', 'Refund decision'), description: t('يتحقق الخادم من حالة الاسترداد والصلاحيات.', 'The server validates refund state and permissions.') });
  const columns: OperationsColumn<Refund>[] = [{ key: 'refund', label: t('الاسترداد', 'Refund'), render: r => <span className="font-mono text-xs">{r.id}</span> }, { key: 'request', label: t('الطلب', 'Request'), render: r => r.requestNumber || '—' }, { key: 'people', label: t('الأطراف', 'Parties'), render: r => <div>{r.customer?.nameAr || r.customer?.nameEn || r.customer?.name || '—'}<div className="text-xs text-muted-foreground">{r.provider?.nameAr || r.provider?.nameEn || r.provider?.name || '—'}</div></div> }, { key: 'amount', label: t('المبلغ', 'Amount'), render: r => `SAR ${r.amount}` }, { key: 'state', label: t('الحالة', 'State'), render: r => r.state || '—' }, { key: 'actions', label: t('إجراءات', 'Actions'), render: r => r.state === 'pending' || r.state === 'requested' ? <div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => act(r, 'approve_refund')}>{t('قبول', 'Approve')}</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => act(r, 'reject_refund')}>{t('رفض', 'Reject')}</Button></div> : null }];
  return <div className="space-y-6">{actionDialog}<div><h1 className="text-3xl font-bold tracking-tight">{t('المستردات', 'Refunds')}</h1><p className="mt-1 text-muted-foreground">{t('مراجعة طلبات استرداد الأموال.', 'Review refund requests.')}</p></div><OperationsTable<Refund> columns={columns} items={data?.items} loading={isLoading} search={search} onSearch={v => { setSearch(v); setCursor(undefined); setHistory([]); }} searchPlaceholder={t('رقم الطلب أو الاسترداد...', 'Request or refund number…')} onDetails={setSelected} nextCursor={data?.nextCursor} hasPrevious={history.length > 0} onNext={() => { if (data?.nextCursor) { setHistory([...history, cursor || '']); setCursor(data.nextCursor); } }} onPrevious={() => { const h = [...history]; const c = h.pop(); setHistory(h); setCursor(c || undefined); }} toolbar={<><select value={state} onChange={e => setState(e.target.value)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="">{t('كل الحالات', 'All states')}</option><option value="pending">{t('قيد الانتظار', 'Pending')}</option><option value="completed">{t('مكتمل', 'Completed')}</option><option value="rejected">{t('مرفوض', 'Rejected')}</option></select><ExportControls resource="refunds" params={{ q: search, state }} /></>} />{selected && <OperationDetails item={selected as unknown as Record<string, unknown>} open onOpenChange={open => !open && setSelected(null)} title={selected.requestNumber || t('تفاصيل الاسترداد', 'Refund details')} fields={[{ label: t('الطلب', 'Request'), value: selected.requestNumber }, { label: t('المبلغ', 'Amount'), value: `SAR ${selected.amount}` }, { label: t('الحالة', 'State'), value: selected.state }, { label: 'Refund ID', value: selected.id, technical: true }]} />}</div>;
}